[package]
name = "fltk-decl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.30"
serde_json = "1"
serde = "1"
serde_derive = "1"
notify = "5.1.0"