[package]
name = "fltk-decl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.30"
serde = "1"
serde_derive = "1"
serde_json5 = "0.1"
serde-xml-rs = "0.6"
notify = { version = "5.1.0", optional = true }
