widget = "Column"

[[children]]
widget = "Button"
label = "Inc"
fixed = 60
id = "inc"
labelcolor = "#0000ff"

[[children]]
widget = "Row"

  [[children.children]]
  widget = "Frame"
  fixed = 30

  [[children.children]]
  widget = "Frame"
  label = "0"
  id = "result"
  labelcolor = "#ff0000"

  [[children.children]]
  widget = "Frame"
  fixed = 30

[[children]]
widget = "Button"
label = "Dec"
fixed = 60
id = "dec"
